### ISSUE TITLE
_pickle.PicklingError: Can't pickle <class 'cPolygon.Error'>: import of module 'cPolygon' failed

### ISSUE THREAD

**Issue by Zhang-O** [whai362/pan_pp.pytorch#10]
more complete log as belows:
Epoch: [1 | 600]
/data/tools/anaconda3/envs/zyl_torch16/lib/python3.7/site-packages/torch/nn/functional.py:2941: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/data/tools/anaconda3/envs/zyl_torch16/lib/python3.7/site-packages/torch/nn/functional.py:3121: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
(1/374) LR: 0.001000 | Batch: 2.668s | Total: 0min | ETA: 17min | Loss: 1.619 | Loss(text/kernel/emb/rec): 0.680/0.193/0.746/0.000 | IoU(text/kernel): 0.324/0.335 | Acc rec: 0.000
Traceback (most recent call last):
  File "/data/tools/anaconda3/envs/zyl_torch16/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/data/tools/anaconda3/envs/zyl_torch16/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'cPolygon.Error'>: import of module 'cPolygon' failed

the code runs normally when using the CTW1500 datasets.
but encounter errors when using my own datasets.

it seems fine in the first run (1/374), what is wrong ? I have no idea.

**Comment by wqtwjt1996** [comment]
Same issue on Total-Text

**Comment by mashumli** [comment]
I also encountered the same problem. How did you solve it?
thank you

**Comment by guoli188** [comment]
I also encountered the same problem. How did you solve it?
thank you

**Comment by wangzixiang99** [comment]
I also encountered the same problem. How did you solve it?
thank you

**Comment by wangzixiang99** [comment]
> I also encountered the same problem. How did you solve it? thank you

How did you solve this problem?
