### ISSUE TITLE
Acc rec: 0.000

### ISSUE THREAD

**Issue by chlg3321** [whai362/pan_pp.pytorch#11]
when I train the PSE, my Acc is 0.00 ？Did u know what is wrong with it ？

LR: 0.000963 | Batch: 0.326s | Total: 1min | ETA: 1min | Loss: 0.111 | Loss(text/kernel/emb/rec): 0.052/0.052/0.006/0.000 | IoU(text/kernel): 0.926/0.811 | Acc rec: 0.000

**Comment by Zhang-O** [comment]
All is fine. Just ignore it . This repo is for detection and has no recognition branch yet.
