### ISSUE TITLE
自己训练的model size和作者提供model大小不一样

### ISSUE THREAD

**Issue by Ycxyue** [whai362/pan_pp.pytorch#110]
psenet model_size:115M
my psenet model_size:230M
pan model_size:49M
my pan model_size:147M
模型是怎么缩小那么多的？

**Comment by Ycxyue** [comment]
仔细打印了一下，原来是作者提供的model只有state_dict；

**Comment by AntyRia** [comment]
> 仔细打印了一下，原来是作者提供的model只有state_dict；

作者提供的model在哪啊
