### ISSUE TITLE
Can I contribute to the post-processing?

### ISSUE THREAD

**Issue by Zerohertz** [whai362/pan_pp.pytorch#114]
Dear Mr. Wang

After reading your paper, I noticed that post-processing code takes up most of the time during model execution. Therefore, I improved the post-processing code as below and confirmed that it is faster than the existing post-processing module.

+ [pa](https://github.com/Zerohertz/pan_pp.pytorch/tree/dev/models/post_processing/pa)

May I send you a pull-request to contribute to this repository?

**Comment by seekingdeep** [comment]
Peace Be Upon You,
it is better that you send the pull request, and allow the developer to have a look.

Also, i have seen the benchmarks that you posted, but what is the percentage of improvement from the original processing against yours

**Comment by Zerohertz** [comment]
Thank you for your comments.

Based on your comment, I will quantitatively evaluate the improvement through the two post-processing function (pa.pyx) and make a pull request for it.
