### ISSUE TITLE
关于Loss的计算

### ISSUE THREAD

**Issue by jewelc92** [whai362/pan_pp.pytorch#12]
代码中在计算EmbLoss时，分为l_agg、l_dis、l_reg，我在论文中并没有看到关于l_reg的内容，如果l_agg和l_dis分别是为了让像素与同一kernel的距离近、与不同kernel的距离远，请问l_reg的具体含义是什么？

**Comment by whai362** [comment]
l_reg是用来限制emb的模长不能太大，有没有这一项估计差别不是很大。
