### ISSUE TITLE
关于后处理的疑问

### ISSUE THREAD

**Issue by jewelc92** [whai362/pan_pp.pytorch#13]
1. 后处理的代码中当kernel中两个连通域的面积比大于max_rate时，将这两个连通域的flag赋值为1，在扩充时，必须同时满足当前扩充的点所属的连通域的flag值为1且与kernal的similar vector距离大于3时才不扩充该点。请问设flag这步操作的作用是什么，直接判断与Kernel的similar vector的距离可以吗？
2. 论文中扩充的点与kernel相似向量的欧式距离thresh值为6，代码中为3，请问实际应用中这个值跟什么有关系，是数据集的某些特点吗？

**Comment by whai362** [comment]
1. 为了减少不必要的similar vector计算，如果两个文本行距离过大，或者大小差别不大，直接合并周围点即可。
2. 应该是3才对（6是笔误），这应该和emb_loss的超参数一致。另外，对于所有数据集都是3。

**Comment by wdsd641417025** [comment]
请问 为什么文本大小差别不大可以直接合并周围点，文本核的面积大小为什么会影响后续的合并处理？

**Comment by tongwei0828** [comment]
> 请问 为什么文本大小差别不大可以直接合并周围点，文本核的面积大小为什么会影响后续的合并处理？ @whai362

我的理解是，PSENet的后处理是先到先得的嘛，对于面积差不多大的时候，抢占的问题不会很明显，但是如果有个面积无敌小但是又跟其他区域有交叠的时候，这个无敌小的可能会因为这种“先到先得”策略，占了很多不属于自己的像素点，同理面积无敌大的时候，就是被抢占了~不知道理解的对不对，但目前也没想到其他更合理的理由了
