### ISSUE TITLE
Trained model save/load with DataParallel.

### ISSUE THREAD

**Issue by yongduek** [whai362/pan_pp.pytorch#14]
Many Thanks for sharing the code of the very good paper.

Model save/load (with DataParallel) can be easier, which was found from here:
https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686/17

Instead of deleting the “module.” string from all the state_dict keys, you can save your model with:
```
torch.save(model.module.state_dict(), path_to_file)
```
instead of
```
torch.save(model.state_dict(), path_to_file)
```
that way you don’t get the “module.” string to begin with…

**Comment by whai362** [comment]
Thanks for your suggestion!
I will solve this problem in the next push.
