### ISSUE TITLE
can not compile sucessfully

### ISSUE THREAD

**Issue by Banyueqin** [whai362/pan_pp.pytorch#15]
running build_ext
building 'pa' extension
gcc -pthread -B /home/dell10/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/dell10/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/home/dell10/anaconda3/include/python3.7m -c pa.cpp -o build/temp.linux-x86_64-3.7/pa.o -O3
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/dell10/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:0,
                 from /home/dell10/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/dell10/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from pa.cpp:554:
/home/dell10/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^
pa.cpp: In function ‘void __Pyx__ExceptionSave(PyThreadState*, PyObject**, PyObject**, PyObject**)’:
pa.cpp:8607:21: error: ‘PyThreadState’ has no member named ‘exc_type’
     *type = tstate->exc_type;
                     ^
pa.cpp:8608:22: error: ‘PyThreadState’ has no member named ‘exc_value’
     *value = tstate->exc_value;
                      ^
pa.cpp:8609:19: error: ‘PyThreadState’ has no member named ‘exc_traceback’
     *tb = tstate->exc_traceback;
                   ^
pa.cpp: In function ‘void __Pyx__ExceptionReset(PyThreadState*, PyObject*, PyObject*, PyObject*)’:
pa.cpp:8616:24: error: ‘PyThreadState’ has no member named ‘exc_type’
     tmp_type = tstate->exc_type;
                        ^
pa.cpp:8617:25: error: ‘PyThreadState’ has no member named ‘exc_value’
     tmp_value = tstate->exc_value;
                         ^
pa.cpp:8618:22: error: ‘PyThreadState’ has no member named ‘exc_traceback’
     tmp_tb = tstate->exc_traceback;
                      ^
pa.cpp:8619:13: error: ‘PyThreadState’ has no member named ‘exc_type’
     tstate->exc_type = type;
             ^
pa.cpp:8620:13: error: ‘PyThreadState’ has no member named ‘exc_value’
     tstate->exc_value = value;
             ^
pa.cpp:8621:13: error: ‘PyThreadState’ has no member named ‘exc_traceback’
     tstate->exc_traceback = tb;
             ^
pa.cpp: In function ‘int __Pyx__GetException(PyThreadState*, PyObject**, PyObject**, PyObject**)’:
pa.cpp:8691:24: error: ‘PyThreadState’ has no member named ‘exc_type’
     tmp_type = tstate->exc_type;
                        ^
pa.cpp:8692:25: error: ‘PyThreadState’ has no member named ‘exc_value’
     tmp_value = tstate->exc_value;
                         ^
pa.cpp:8693:22: error: ‘PyThreadState’ has no member named ‘exc_traceback’
     tmp_tb = tstate->exc_traceback;
                      ^
pa.cpp:8694:13: error: ‘PyThreadState’ has no member named ‘exc_type’
     tstate->exc_type = local_type;
             ^
pa.cpp:8695:13: error: ‘PyThreadState’ has no member named ‘exc_value’
     tstate->exc_value = local_value;
             ^
pa.cpp:8696:13: error: ‘PyThreadState’ has no member named ‘exc_traceback’
     tstate->exc_traceback = local_tb;
             ^
error: command 'gcc' failed with exit status 1

**Comment by whai362** [comment]
My gcc version is 5.4.
