### ISSUE TITLE
能否提供训练好的模型的链接

### ISSUE THREAD

**Issue by shaohailin** [whai362/pan_pp.pytorch#18]

**Comment by whai362** [comment]
模型在https://github.com/whai362/pan_pp.pytorch/tree/master/config/pan下能找到

**Comment by zcswdt** [comment]
> 模型在[https://github.com/whai362/pan_pp.pytorch/tree/master/config/pan下能找到](https://github.com/whai362/pan_pp.pytorch/tree/master/config/pan%E4%B8%8B%E8%83%BD%E6%89%BE%E5%88%B0)

您好，链接失效了，是否可以提供一下新的链接呢，谢谢
