### ISSUE TITLE
训练数据模拟

### ISSUE THREAD

**Issue by mayidu** [whai362/pan_pp.pytorch#20]
您好！请问训练数据，弯曲的，如果模拟生成呢？

**Comment by whai362** [comment]
模拟生成是什么意思？abcnet论文里有提到过弯曲文本的合成，他们也公开了一个弯曲文本合成的数据集。

**Comment by mayidu** [comment]
感谢您的回复，请问您有没有相关弯曲文本合成的论文或者代码，我好像很久之前看到过pse对应的弯曲文本合成，但是现在找不到了，时间有点久，不知道是否记错了，感谢！
