### ISSUE TITLE
关于训练的问题

### ISSUE THREAD

**Issue by mayidu** [whai362/pan_pp.pytorch#21]
您好！我现在在自己的数据上进行训练，训练过程是这样的
![image](https://user-images.githubusercontent.com/29938271/105050254-8eb27e00-5aa8-11eb-8d16-0d5d65c66fb6.png)
Epoch: [212 | 600]
(1/198) LR: 0.000677 | Batch: 3.934s | Total: 0min | ETA: 13min | Loss: 0.752 | Loss(text/kernel/emb/rec): 0.493/0.199/0.059/0.000 | IoU(text/kernel): 0.055/0.553 | Acc rec: 0.000
(21/198) LR: 0.000677 | Batch: 1.089s | Total: 0min | ETA: 3min | Loss: 0.731 | Loss(text/kernel/emb/rec): 0.478/0.199/0.054/0.000 | IoU(text/kernel): 0.048/0.482 | Acc rec: 0.000
(41/198) LR: 0.000677 | Batch: 1.022s | Total: 1min | ETA: 3min | Loss: 0.732 | Loss(text/kernel/emb/rec): 0.478/0.198/0.056/0.000 | IoU(text/kernel): 0.049/0.476 | Acc rec: 0.000
这个Acc rec一直是0，我终止训练后，在测试数据上进行测试时，output输出的是空的，请问是怎么回事呢，感谢啦！

**Comment by mayidu** [comment]
您好，上一个问题我解决了，是数据的问题，然后可以正常训练，效果如下图
![image](https://user-images.githubusercontent.com/29938271/105310864-4013f980-5bf8-11eb-8cf6-98a24446725c.png)
w
我训练这么多后，终止训练，输出的结果有值，但是感觉效果很差，如果下图所示
![image](https://user-images.githubusercontent.com/29938271/105311429-65086c80-5bf8-11eb-966a-aff31f167209.png)

想问一下s是哪里出错了呢，我训练了有近一天24小时的时间，差不多20个小时左右吧，开始的时候IOU的值挺好的，后来就特别慢了，是学习率的问题吗，感谢啦

**Comment by whai362** [comment]
1. Acc rec是识别准确率，目前这个代码没有识别分支。是0没有问题。
2. iou值后来确实会涨得比较慢。
3. 你看看把dataloader的数据可视化出来看看是不是对了，我猜是数据没有给对。
4. 看log训练图像貌似可以收敛，你把训练图片送进去测试看看呢？看是不是效果依旧差？

**Comment by mayidu** [comment]
特别感谢您的回复，问题已经解决了，是输入点的顺序问题！
我想问一下，使用pan文本检测得到结果后，送到ocr去识别，那得到的检测结果数据要如何处理一下呢，您有没有后续识别的一些研究，感谢！
