### ISSUE TITLE
文本检测有粘连的情况如何解决？

### ISSUE THREAD

**Issue by mayidu** [whai362/pan_pp.pytorch#23]
您好！我现在针对特定的问题进行文本检测模型，但是有的时候会出来上下两行检测为一个的情况，我增加了一下重合的数据，但是效果也不是特别理想，这种情况依然存在，请问一下您这样该如何有效的避免或者解决
![image](https://user-images.githubusercontent.com/29938271/108578370-5af39e00-735d-11eb-99f5-ee0b2d66fbea.png)

**Comment by Mafengqiang** [comment]
> 您好！我现在针对特定的问题进行文本检测模型，但是有的时候会出来上下两行检测为一个的情况，我增加了一下重合的数据，但是效果也不是特别理想，这种情况依然存在，请问一下您这样该如何有效的避免或解决
> ![图像](https://user-images.githubusercontent.com/29938271/108578370-5af39e00-735d-11eb-99f5-ee0b2d66fbea.png)

这个数据配置文件怎么修改啊，你是用自己的数据集训练的吗，感谢回复

**Comment by mayidu** [comment]
嗯，我是用自己的训练集，你看dataset里面pan，作者给了对于几个数据集的例子，看着改一下就行，或者自己按自己的数据集写一下

**Comment by Mafengqiang** [comment]
> 嗯，我是用自己的训练集，你看dataset里面pan，作者给了对于几个数据集的例子，看着改一下就行，或者自己按自己的数据集写一下

嗯嗯，谢谢你了，还有那个训练数据集标签的格式是什么样的呢，方便给截个图看一下吗，谢谢！

**Comment by Mafengqiang** [comment]
> 嗯，我是用自己的训练集，你看dataset里面pan，作者给了对于几个数据集的例子，看着改一下就行，或者自己按自己的数据集写一下

您好，方便用邮箱联系一下吗，最近在用这个PANet做一个文本检测，有一点问题想请教一下，十分感谢！875452380@qq.com

**Comment by mayidu** [comment]
数据集标签就是文本框的坐标，x,y，然后坐标的话得有顺序，就是要能行成一个闭环

**Comment by Mafengqiang** [comment]
> 数据集标签就是文本框的坐标，x,y，然后坐标的话得有顺序，就是要能行成一个闭环
您好，再打扰一下，为什么我用他的预训练模型画出来的框差了90度呢，
![image](https://user-images.githubusercontent.com/44855506/109152363-5b00fd00-77a6-11eb-8f17-cac0649073a7.png)，你有碰到这个问题吗，我是用他的预训练模型测试输出的标签文本画的

**Comment by mayidu** [comment]
x,y坐标反了，你把xy坐标兑换一下就行，作者test里面输出到文本的坐标是y,x形式的

**Comment by Mafengqiang** [comment]
> x,y坐标反了，你把xy坐标兑换一下就行，作者test里面输出到文本的坐标是y,x形式的

嗯嗯，可以啦，谢谢了，还有这个测试图像的时候可以只对图像的一部分进行文本检测吗，就是在一整张图像中限定一部分区域，对这部分区域进行文本检测，这个参数可以在哪里设置吗，这个你有了解过吗

**Comment by mayidu** [comment]
只对部分区域，你就截取你要识别的区域就行了吧，或者你的测试数据都只识别这个区域的话，你就训练一个只识别这个区域的模型吧，作者给的模型应该是通用的

**Comment by Mafengqiang** [comment]
> 只对部分区域，你就截取你要识别的区域就行了吧，或者你的测试数据都只识别这个区域的话，你就训练一个只识别这个区域的模型吧，作者给的模型应该是通用的

老师，你好，还有个问题想去请教一下你，因为我是检测这种印章上的弯曲文本，在数据标注的时候需要标注多个点，这个多点标注工具有没有推荐的啊，最好能把文字内容也能标上，因为后期检测出来之后要做文字识别，麻烦老师了

**Comment by Mafengqiang** [comment]
> 只对部分区域，你就截取你要识别的区域就行了吧，或者你的测试数据都只识别这个区域的话，你就训练一个只识别这个区域的模型吧，作者给的模型应该是通用的

老师，你好，还有个问题想去请教一下你，因为我是检测这种印章上的弯曲文本，在数据标注的时候需要标注多个点，这个多点标注工具有没有推荐的啊，最好能把文字内容也能标上，因为后期检测出来之后要做文字识别，麻烦老师了

**Comment by Floyd809** [comment]
> 嗯，我是用自己的训练集，你看dataset里面pan，作者给了对于几个数据集的例子，看着改一下就行，或者自己按自己的数据集写一下

请问除了dataset 的脚本需要修改 还有其他地方要改吗

**Comment by WeichangChen2020** [comment]
请问vocabulary的内容是根据标签生成的还是啥

**Comment by WeichangChen2020** [comment]
请问vocabulary的内容是根据标签生成的还是啥。
作者给出的代码只有英文加数字的vocabulary，所以对于中文我不是很明白（纯新手）。

**Comment by WeichangChen2020** [comment]
另外如何在图片中框出这种不规则图形，我看到网络的输出只有8个坐标啊
