### ISSUE TITLE
eval   ic15    Error! No module named numpy

### ISSUE THREAD

**Issue by a885041573** [whai362/pan_pp.pytorch#27]
eval   ic15    Error! No module named numpy

**Comment by whai362** [comment]
`pip2 install numpy`

**Comment by a885041573** [comment]
Thanks


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "whai362/pan_pp.pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月6日(星期二) 下午3:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [whai362/pan_pp.pytorch] eval   ic15    Error! No module named numpy (#27)





 
pip2 install numpy
