### ISSUE TITLE
test Pan on single image

### ISSUE THREAD

**Issue by seekingdeep** [whai362/pan_pp.pytorch#31]
@whai362 @RoseSakurai Hi there,
I want to test Pan on a single image, is there a script to do that

**Comment by bharatsubedi** [comment]
@seekingdeep did you prepare a code for testing with single images? I also want to test with a single image. Could you please share your code?

**Comment by lrfighting** [comment]
> @seekingdeep did you prepare a code for testing with single images? I also want to test with a single image. Could you please share your code?

 did you prepare a code for testing with single images? I also want to test with a single image. Could you please share your code?  Thank  you !
