### ISSUE TITLE
Testing issues

### ISSUE THREAD

**Issue by suresh-s** [whai362/pan_pp.pytorch#35]
I have tested the model with "Total-text" dataset with your trained model.

I tried to draw the bounding boxes on the images using **outputs['bboxes']**.  But i couldn't.  I have used the following code.

```
for bbox in enumerate(bboxes):
      draw = ImageDraw.Draw(img)
      color = tuple(np.random.choice(range(100, 256), size=3))
      draw.polygon(bbox, outline=color)
return img
```

But resultant image does not have the bounding box

1. what is wrong in this code?
2. There is no code for calculating the Precision %, Recall %  and F-measure % at Test function. How the Precision %, Recall %  and F-measure % is calculated?

**Comment by czczup** [comment]
Test scripts are in this [directory](https://github.com/whai362/pan_pp.pytorch/tree/master/eval)
