### ISSUE TITLE
Backbone Resnet101 - Training time error

### ISSUE THREAD

**Issue by suresh-s** [whai362/pan_pp.pytorch#36]
I have changed the backbone to Resnet101 and started the training,

got the following error 

**RuntimeError: Given groups=1, weight of size 128 64 1 1, expected input[8, 256, 160, 160] to have 64 channels, but got 256 channels instead**

Could you tell me the reason for this error?

**Comment by czczup** [comment]
The out channels of the four stages in R101 are 256, 512, 1024, 2048 respectively.
You should set in_channels=(256, 512, 1024, 2048) in the config file.
