### ISSUE TITLE
Datasets about training pan++

### ISSUE THREAD

**Issue by WeitaoJ** [whai362/pan_pp.pytorch#47]
Hi, I want to train pan++, but I don't know the format of dataset, especially the total text which have multiple version, could you provide the detailed data structure or the link to the dataset you used, thank you!

**Comment by czczup** [comment]
We add a readme.md file to illustrate the paths of datasets. Please refer to this [page](https://github.com/whai362/pan_pp.pytorch/tree/master/dataset) to download and place these datasets.
