### ISSUE TITLE
ModuleNotFoundError: No module named 'models.post_processing.pse_v2'

### ISSUE THREAD

**Issue by WeitaoJ** [whai362/pan_pp.pytorch#48]
these is no pse_v2
![image](https://user-images.githubusercontent.com/48707121/124540509-1b33db80-de52-11eb-8a92-d4376b40071e.png)

**Comment by SherlockHua1995** [comment]
YES. Waiting for update.

**Comment by WeitaoJ** [comment]
> YES. Waiting for update.

So, how long do I need to wait?

**Comment by huangzhhhhh** [comment]
We have fixed this problem in last update.

**Comment by WeitaoJ** [comment]
> We have fixed this problem in last update.

whether pse and pse_v2 are the same?

**Comment by huangzhhhhh** [comment]
> > We have fixed this problem in last update.
> 
> whether pse and pse_v2 are the same?

yes, these two modules are same.
