### ISSUE TITLE
not sure about run compile.sh

### ISSUE THREAD

**Issue by Zhang-O** [whai362/pan_pp.pytorch#5]
(zyl_torch16) ubuntu@ubuntu:/data/zhangyl/pan_pp.pytorch-master$ sh ./compile.sh 
Compiling pa.pyx because it depends on /data/tools/anaconda3/envs/zyl_torch16/lib/python3.7/site-packages/numpy/__init__.pxd.
[1/1] Cythonizing pa.pyx
/data/tools/anaconda3/envs/zyl_torch16/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /data/zhangyl/pan_pp.pytorch-master/models/post_processing/pa/pa.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running build_ext
building 'pa' extension
creating build
creating build/temp.linux-x86_64-3.7
gcc -pthread -B /data/tools/anaconda3/envs/zyl_torch16/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/data/tools/anaconda3/envs/zyl_torch16/lib/python3.7/site-packages/numpy/core/include -I/data/tools/anaconda3/envs/zyl_torch16/include/python3.7m -c pa.cpp -o build/temp.linux-x86_64-3.7/pa.o -O3
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /data/tools/anaconda3/envs/zyl_torch16/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                 from /data/tools/anaconda3/envs/zyl_torch16/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /data/tools/anaconda3/envs/zyl_torch16/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from pa.cpp:647:
/data/tools/anaconda3/envs/zyl_torch16/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
g++ -pthread -shared -B /data/tools/anaconda3/envs/zyl_torch16/compiler_compat -L/data/tools/anaconda3/envs/zyl_torch16/lib -Wl,-rpath=/data/tools/anaconda3/envs/zyl_torch16/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/pa.o -o /data/zhangyl/pan_pp.pytorch-master/models/post_processing/pa/pa.cpython-37m-x86_64-linux-gnu.so
(zyl_torch16) ubuntu@ubuntu:/data/zhangyl/pan_pp.pytorch-master$

this is the compile history, I am not sure whether is successully build or not.

**Comment by whai362** [comment]
After successfully compiling, you will get "pa.cpython-36m-x86_64-linux-gnu.so" in folder "pan_pp.pytorch/models/post_processing/pa".

**Comment by Zhang-O** [comment]
> After successfully compiling, you will get "pa.cpython-36m-x86_64-linux-gnu.so" in folder "pan_pp.pytorch/models/post_processing/pa".

Ｉ checked the path that pa.cpython-37m-x86_64-linux-gnu.so does exist in "pan_pp.pytorch-master/models/post_processing/pa". I will run the training processing to test it .

Thanks a lot!
