### ISSUE TITLE
AttributeError: 'PAN_PP_jointTrain' object has no attribute 'voc'

### ISSUE THREAD

**Issue by dikubab** [whai362/pan_pp.pytorch#50]
How to resolve the 'AttributeError: 'PAN_PP_jointTrain' object has no attribute 'voc''
![Screen Shot 2021-07-12 at 4 13 32 PM](https://user-images.githubusercontent.com/60455687/125254460-1036ea80-e32d-11eb-867f-a472fa97bfbd.png)

**Comment by huangzhhhhh** [comment]
In the latest version, the "voc" is an attribute of dataloader, please check if you are using the up-to-date code, or describe the problem more specifically (such as the error is reported by which line?).

![image](https://user-images.githubusercontent.com/46897452/125236621-e5419c00-e316-11eb-9992-96f4591728b8.png)

**Comment by dikubab** [comment]
Thank you very much for the response. I am actually using the updated version. I couldn't find a code that has the above screenshot. I tried to search in  ./dataset/pan_pp/pan_pp_jointTrain.py in the dataset folder, it is not included. Please would mind linking the code with your repo. Thank you very much in advance for your time and commitment.
