### ISSUE TITLE
加了recognition_head，识别结果没有文字

### ISSUE THREAD

**Issue by WeichangChen2020** [whai362/pan_pp.pytorch#55]
我仿照jointTrain的config，在网络中加了recognition_head，为何最终测试的结果只有8个坐标没有文字结果
model = dict(
    type='PAN_PP',
    backbone=dict(
        type='resnet18',
        pretrained=True
    ),
    neck=dict(
        type='FPEM_v2',
        in_channels=(64, 128, 256, 512),
        out_channels=128
    ),
    detection_head=dict(
        type='PAN_PP_DetHead',
        in_channels=512,
        hidden_dim=128,
        num_classes=6,
        loss_text=dict(
            type='DiceLoss',
            loss_weight=1.0
        ),
        loss_kernel=dict(
            type='DiceLoss',
            loss_weight=0.5
        ),
        loss_emb=dict(
            type='EmbLoss_v2',
            feature_dim=4,
            loss_weight=0.25
        ),
        use_coordconv=False,
    ),
    recognition_head=dict(
        type='PAN_PP_RecHead',
        input_dim=512,
        hidden_dim=128,
        feature_size=(8, 32)
    )
)
data = dict(
    batch_size=2,
    train=dict(
        type='PAN_PP_TT',
        split='train',
        is_transform=True,
        img_size=736,
        short_size=736,
        kernel_scale=0.5,
        read_type='pil',
        with_rec=True
    ),
    test=dict(
        type='PAN_PP_TT',
        split='test',
        short_size=720,
        read_type='pil',
        with_rec=True
    )
)
train_cfg = dict(
    lr=1e-3,
    schedule='polylr',
    epoch=10,
    optimizer='Adam',
    use_ex=False,
)
test_cfg = dict(
    min_score=0.8,
    min_area=260,
    min_kernel_area=2.6,
    scale=4,
    bbox_type='rect',
    result_path='outputs/submit_TT_rec',
    rec_post_process=dict(
        len_thres=3,
        score_thres=0.95,
        unalpha_score_thres=0.9,
        ignore_score_thres=0.93,
        editDist_thres=2,
        voc_path=None  # './data/total_text/ppocr_keys_v1.txt' #'./data/ICDAR2015/Challenge4/GenericVocabulary.txt'
    ),
)

**Comment by carolyueyueyue** [comment]
有识别结果吗？朋友
