### ISSUE TITLE
提示加载ZIP文件错误

### ISSUE THREAD

**Issue by Mrz12121** [whai362/pan_pp.pytorch#57]
![image](https://user-images.githubusercontent.com/56107092/130947588-1ad9364a-b8be-41e7-bf5a-6b3975d0dfc3.png)
请问这是什么原因呢

**Comment by czczup** [comment]
试试看把output文件夹里的zip删了重新测试

**Comment by BigWhit** [comment]
同问，两个文件都解压后，还是报这个错，output文件夹里也没有zip

**Comment by czczup** [comment]
> 同问，两个文件都解压后，还是报这个错，output文件夹里也没有zip

要先运行test.py生成zip再运行eval.sh

**Comment by BigWhit** [comment]
> 要先运行test.py生成zip再运行eval.sh
运行了test.py，outputs里生成的submit_ic15只是一个文件夹，不是zip，应该不影响吧

**Comment by czczup** [comment]
> > 要先运行test.py生成zip再运行eval.sh
> > 运行了test.py，outputs里生成的submit_ic15只是一个文件夹，不是zip，应该不影响吧

![image](https://user-images.githubusercontent.com/23737120/135229975-574de76e-7a2a-47b1-9657-acf47fdd321d.png)
应该是有zip的，eval_ic15.sh里读取的也是submit_ic15.zip，你看看

**Comment by czczup** [comment]
![image](https://user-images.githubusercontent.com/23737120/135230772-c0cf50bf-9012-4c2c-8c44-505230612d92.png)

**Comment by Mrz12121** [comment]
您好，我没用使用joint train，我仅对ic15进行了训练，在output文件夹下生成了submit_ic15 和submit_ic15.zip，没有_rec的后缀，当我尝试运 行 ./eval_ic15.sh 时，抛出如下异常
![image](https://user-images.githubusercontent.com/56107092/136012235-0b3e0481-1953-4f62-a498-d8ff1b7c3d6d.png)
请问这个只能在联合训练下使用吗

**Comment by Mrz12121** [comment]
![image](https://user-images.githubusercontent.com/56107092/136012663-35427d18-03fe-4108-9e86-8b0ceed2cc13.png)
这是我运行test.py文件的代码，我自己的环境中也有Polygon包 == 3.0.7，还请大佬解惑

**Comment by czczup** [comment]
> ![image](https://user-images.githubusercontent.com/56107092/136012663-35427d18-03fe-4108-9e86-8b0ceed2cc13.png) 这是我运行test.py文件的代码，我自己的环境中也有Polygon包 == 3.0.7，还请大佬解惑

你好，因为这个eval代码是用python2运行的，所以得在python2的环境里也有polygon，只要`pip2 install polygon2`就可以了。

**Comment by Mrz12121** [comment]
> > ![image](https://user-images.githubusercontent.com/56107092/136012663-35427d18-03fe-4108-9e86-8b0ceed2cc13.png) 这是我运行test.py文件的代码，我自己的环境中也有Polygon包 == 3.0.7，还请大佬解惑
> 
> 你好，因为这个eval代码是用python2运行的，所以得在python2的环境里也有polygon，只要`pip2 install polygon2`就可以了。

感谢您的解答，已经运行成功了~

**Comment by xingchen-yao** [comment]
> > > ![image](https://user-images.githubusercontent.com/56107092/136012663-35427d18-03fe-4108-9e86-8b0ceed2cc13.png) 这是我运行test.py文件的代码，我自己的环境中也有Polygon包 == 3.0.7，还请大佬解惑
> > 
> > 
> > 你好，因为这个eval代码是用python2运行的，所以得在python2的环境里也有polygon，只要`pip2 install polygon2`就可以了。
> 
> 感谢您的解答，已经运行成功了~

请问必须要用python2运行吗，我改成了python，然后运行报错
![image](https://user-images.githubusercontent.com/92241494/181740691-d97d9ef6-64f7-44cc-9c55-9c030497ba17.png)

**Comment by kai1980** [comment]
> 试着把输出的文件夹测试里的zip压缩了重新



> > ![图片](https://user-images.githubusercontent.com/56107092/136012663-35427d18-03fe-4108-9e86-8b0ceed2cc13.png)这是我运行test.py文件的代码，我自己的环境中也有Polygon包== 3.0.7，还请大佬解惑
> 
> 你好，因为这个eval代码是用python2运行的，所以必须在python2的环境里也有多边形，只要`pip2 install polygon2`就可以了。

大佬，pythorn2和pythorn3的环环境训练的时候能自动切换？还是只能在虚拟机上跑，输入pip2这个指令的时候显示失败
