### ISSUE TITLE
I have not seen the description of FPEMv2 in "PAN++" paper?

### ISSUE THREAD

**Issue by zhazhabiu** [whai362/pan_pp.pytorch#59]
When I saw the model building code of PAN++, found a structure called "FPEMv2".
I know that "FPEMv1" is the enhancement module proposed in paper, but have no idea about "FPEMv2".
Is it newly presented? Or I‘ve ignored something?

**Comment by czczup** [comment]
Hi, please see Section 4.5 and Figure 5 in the PAN++ paper.
The FPEM (improved) is FPEMv2 in the code.
The difference is that FPEMv1 uses vanilla conv, while FPEMv2 uses dwconv.
