### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by shengtao96** [whai362/pan_pp.pytorch#6]
Thanks for your excellent work! I follow all your settings and train the PAN model on the Total-text dataset, but can't reach the results as you report in the paper.

I run the commond 'CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py config/pan/pan_r18_tt.py', and the F1-score is 83.0 (83.5 in the paper). The small difference is fine.

I run the commond 'CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py config/pan/pan_r18_synth.py' to pretrain the PAN, and 'CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py config/pan/pan_r18_tt_finetune.py' to finetune the model. The Final score is 83.5(85.0 in the paper).

Why I get the bad results? Could you provide the training logs?

**Comment by whai362** [comment]
Sorry, I didn't save training logs.
