### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'resume'

### ISSUE THREAD

**Issue by lrjj** [whai362/pan_pp.pytorch#68]
PAN++ic15，An error appears when trying to test the model:

reading type: pil.
Traceback (most recent call last):
  File "test.py", line 155, in <module>
    main(args)
  File "test.py", line 138, in main
    print("No checkpoint found at '{}'".format(args.resume))
AttributeError: 'Namespace' object has no attribute 'resume'

**Comment by silence-smart** [comment]
你好，请问具体是在哪里添加呢？
