### ISSUE TITLE
morphology operations from kornia

### ISSUE THREAD

**Issue by ducha-aiki** [whai362/pan_pp.pytorch#70]
Hi,

Your FAST paper is really amazing! 
While you already have an implementation of erosion/dilation, let me offer using our set of morphology, implemented in pyre pytorch:
https://kornia.readthedocs.io/en/latest/morphology.html

https://kornia-tutorials.readthedocs.io/en/master/morphology_101.html

Best, Dmytro.

**Comment by czczup** [comment]
@ducha-aiki Thanks.
