### ISSUE TITLE
Finetune   中的 N 和Y ？

### ISSUE THREAD

**Issue by lrfighting** [whai362/pan_pp.pytorch#76]
请问有大佬知道 作者的评估表格中 Finetune中 N和Y是啥意思吗。为啥差别那么大

**Comment by czczup** [comment]
> 请问有大佬知道 作者的评估表格中 Finetune中 N和Y是啥意思吗。为啥差别那么大

N就是没用SynthText预训练的模型，所以点会低一些。

**Comment by lrfighting** [comment]
> > 请问有大佬知道 作者的评估表格中 Finetune中 N和Y是啥意思吗。为啥差别那么大
> 
> N就是没用SynthText预训练的模型，所以点会低一些。

好的好的，谢谢大佬，请问如何进行预训练呢？或者预训练的模型如何获得呢？作者有没有提供啊

**Comment by czczup** [comment]
> > > 请问有大佬知道 作者的评估表格中 Finetune中 N和Y是啥意思吗。为啥差别那么大
> > 
> > 
> > N就是没用SynthText预训练的模型，所以点会低一些。
> 
> 好的好的，谢谢大佬，请问如何进行预训练呢？或者预训练的模型如何获得呢？作者有没有提供啊

有，synthtext那个config就是预训练
