### ISSUE TITLE
Config  and Finetune?

### ISSUE THREAD

**Issue by lrfighting** [whai362/pan_pp.pytorch#79]
What do N and Y mean in Finetune?
I looked at the config at the back of the table, but I didn't find the difference?

![image](https://user-images.githubusercontent.com/80096466/144712113-169aabe7-0af4-4ad6-975f-7dfb2bf9d400.png)

**Comment by czczup** [comment]
> What do N and Y mean in Finetune? I looked at the config at the back of the table, but I didn't find the difference?
> 
> ![image](https://user-images.githubusercontent.com/80096466/144712113-169aabe7-0af4-4ad6-975f-7dfb2bf9d400.png)

Hi, N means No, and Y means Yes.
These configs are different in train_cfg.
For example:
```
train_cfg = dict(
    lr=1e-3,
    schedule='polylr',
    epoch=600,
    optimizer='Adam',
    pretrain='checkpoints/pan_r18_synth/checkpoint_1ep.pth.tar' # Notice here
)
```
