### ISSUE TITLE
执行训练代码时出错

### ISSUE THREAD

**Issue by huahuabai** [whai362/pan_pp.pytorch#94]
博主您好，按照您的步骤运行遇到了如下错误![image](https://user-images.githubusercontent.com/55180640/168425652-b2ad3b22-35d9-4c58-9887-d81687eec606.png)

**Comment by huahuabai** [comment]
> 我也出现了这个问题，请问您是怎么解决的

把跟--debug相关的内容隐掉就行

**Comment by smama65** [comment]
would you explain more?
